#!/usr/bin/env python3
"""
cw (CodeWatch) — Wrap CLI commands and notify when they need attention.

Usage:
    cw codex "fix the bug"
    cw claude
    cw --stall-timeout 20 --notify-delay 30 codex "build feature"
    cw init --aliases              # install shell aliases

Detects:
    - Process waiting for input (no output for N seconds)
    - Process exited successfully
    - Process exited with error

Install:
    curl -fsSL https://raw.githubusercontent.com/wuchengbin/codewatch/main/install.sh | sh
"""

import sys
import os
import pty
import select
import time
import subprocess
import signal
import fcntl
import termios

VERSION = "0.2.0"

DEFAULT_STALL_TIMEOUT = 30
DEFAULT_NOTIFY_DELAY = 60

SHELL_RC = os.path.expanduser("~/.zshrc")

ALIAS_BLOCK_START = "# >>> cw (CodeWatch) >>>"
ALIAS_BLOCK_END   = "# <<< cw (CodeWatch) <<<"
ALIAS_BLOCK = f"""{ALIAS_BLOCK_START}
# Auto-generated by 'cw init --aliases'. Run 'cw init --uninstall-aliases' to remove.
alias codex='cw codex'
alias claude='cw claude'
{ALIAS_BLOCK_END}"""


# ─── Notification ──────────────────────────────────────────────────────

def notify(title, message):
    safe_title = title.replace("\\", "\\\\").replace('"', '\\"')
    safe_msg = message.replace("\\", "\\\\").replace('"', '\\"')
    script = (
        f'display notification "{safe_msg}" with title "{safe_title}" '
        f'sound name "Glass"'
    )
    os.system(f"osascript -e '{script}'")


# ─── I/O ───────────────────────────────────────────────────────────────

def set_nonblocking(fd):
    flags = fcntl.fcntl(fd, fcntl.F_GETFL)
    fcntl.fcntl(fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)


# ─── Core monitor ──────────────────────────────────────────────────────

def run_command(cmd, stall_timeout, notify_delay):
    master_fd, slave_fd = pty.openpty()

    try:
        winsize = fcntl.ioctl(sys.stdin.fileno(), termios.TIOCGWINSZ, b'\0' * 8)
        fcntl.ioctl(slave_fd, termios.TIOCSWINSZ, winsize)
    except OSError:
        pass

    proc = subprocess.Popen(
        cmd,
        stdin=slave_fd,
        stdout=slave_fd,
        stderr=slave_fd,
        close_fds=True,
        preexec_fn=os.setsid,
    )
    os.close(slave_fd)
    set_nonblocking(master_fd)

    stdin_fd = sys.stdin.fileno()
    stdout_fd = sys.stdout.fileno()

    last_output_time = time.time()
    last_input_time = time.time()
    stall_notified = False
    exit_notified = False
    pending_notifies = []
    exit_code = None

    def fire_pending():
        now = time.time()
        to_fire = []
        remaining = []
        for t, title, msg in pending_notifies:
            elapsed = now - t
            user_active = (now - last_input_time) < notify_delay
            if elapsed >= notify_delay:
                if not user_active:
                    to_fire.append((title, msg))
            else:
                remaining.append((t, title, msg))
        pending_notifies.clear()
        pending_notifies.extend(remaining)
        for title, msg in to_fire:
            notify(title, msg)

    def schedule(title, msg):
        for _, t, _ in pending_notifies:
            if t == title:
                return
        pending_notifies.append((time.time(), title, msg))

    def on_sigwinch(signum, frame):
        try:
            ws = fcntl.ioctl(stdin_fd, termios.TIOCGWINSZ, b'\0' * 8)
            fcntl.ioctl(master_fd, termios.TIOCSWINSZ, ws)
        except OSError:
            pass

    signal.signal(signal.SIGWINCH, on_sigwinch)

    cmd_str = " ".join(cmd)
    sys.stderr.write(
        f"\033[2m cw ⏱  monitoring: {cmd_str}  "
        f"(stall={stall_timeout}s, notify={notify_delay}s)\033[0m\n"
    )

    try:
        while True:
            now = time.time()
            poll_ret = proc.poll()

            if poll_ret is None and not stall_notified:
                if (now - last_output_time) > stall_timeout:
                    schedule("⏳ CodeWatch", f"{cmd_str} — 可能等待输入")
                    stall_notified = True

            if poll_ret is not None and not exit_notified:
                exit_code = poll_ret
                if exit_code == 0:
                    schedule("✅ CodeWatch", f"{cmd_str} — 已完成")
                else:
                    schedule("❌ CodeWatch", f"{cmd_str} — 失败 (exit {exit_code})")
                exit_notified = True

            fire_pending()

            read_fds = [stdin_fd]
            if poll_ret is None:
                read_fds.append(master_fd)

            try:
                ready, _, _ = select.select(read_fds, [], [], 1.0)
            except (select.error, ValueError, OSError):
                if exit_notified and not pending_notifies:
                    break
                continue

            for fd in ready:
                if fd == master_fd:
                    try:
                        data = os.read(master_fd, 65536)
                        if data:
                            os.write(stdout_fd, data)
                            last_output_time = time.time()
                            stall_notified = False
                    except OSError:
                        pass
                elif fd == stdin_fd:
                    try:
                        data = os.read(stdin_fd, 65536)
                        if data:
                            os.write(master_fd, data)
                            last_input_time = time.time()
                            stall_notified = False
                    except OSError:
                        pass

            if exit_notified and not pending_notifies:
                break

    except KeyboardInterrupt:
        proc.terminate()
        proc.wait()
        sys.stderr.write("\n\033[2m cw: interrupted\033[0m\n")

    try:
        while True:
            ready, _, _ = select.select([master_fd], [], [], 0.3)
            if not ready:
                break
            data = os.read(master_fd, 65536)
            if not data:
                break
            os.write(stdout_fd, data)
    except OSError:
        pass

    os.close(master_fd)

    if exit_code is None:
        proc.wait()
        exit_code = proc.returncode

    return exit_code


# ─── Init ───────────────────────────────────────────────────────────────

def init_aliases():
    rc_path = SHELL_RC
    if not os.path.exists(rc_path) and os.path.exists(os.path.expanduser("~/.bashrc")):
        rc_path = os.path.expanduser("~/.bashrc")

    if os.path.exists(rc_path):
        with open(rc_path) as f:
            content = f.read()
        if ALIAS_BLOCK_START in content:
            print(f"✓ Aliases already in {rc_path}")
            return

    with open(rc_path, "a") as f:
        f.write(f"\n{ALIAS_BLOCK}\n")

    print(f"✓ Aliases added to {rc_path}")
    print(f"  Run: source {rc_path}")
    print(f"")
    print(f"  codex \"fix the bug\"   # automatically wrapped with cw")
    print(f"  claude                  # automatically wrapped with cw")


def uninstall_aliases():
    rc_path = SHELL_RC
    if not os.path.exists(rc_path) and os.path.exists(os.path.expanduser("~/.bashrc")):
        rc_path = os.path.expanduser("~/.bashrc")

    if not os.path.exists(rc_path):
        print("No shell RC found")
        return

    with open(rc_path) as f:
        lines = f.readlines()

    in_block = False
    new_lines = []
    for line in lines:
        if line.strip() == ALIAS_BLOCK_START:
            in_block = True
            continue
        if line.strip() == ALIAS_BLOCK_END:
            in_block = False
            if new_lines and new_lines[-1].strip() == "":
                new_lines.pop()
            continue
        if in_block:
            continue
        new_lines.append(line)

    with open(rc_path, "w") as f:
        f.writelines(new_lines)

    print(f"✓ Aliases removed from {rc_path}")
    print(f"  Run: source {rc_path}")


# ─── CLI (manual parse — avoids argparse subcommand conflicts) ─────────

def usage():
    print(f"""cw {VERSION} — CodeWatch: wrap CLI commands and notify on attention events

Usage:
    cw [options] <command> [args...]
    cw init --aliases
    cw init --uninstall-aliases

Options:
    --stall-timeout SEC   No output for SEC seconds → consider stalled (default: {DEFAULT_STALL_TIMEOUT})
    --notify-delay SEC    Wait SEC seconds after trigger before notifying (default: {DEFAULT_NOTIFY_DELAY})
    --version             Show version
    -h, --help            Show this help

Examples:
    cw codex "fix the bug"
    cw claude
    cw --stall-timeout 20 npm test
    cw init --aliases     # add shell aliases for codex/claude

Triggers:
    ⏳ Waiting for input  — no output for {DEFAULT_STALL_TIMEOUT}s while process alive
    ✅ Completed          — process exited with code 0
    ❌ Failed             — process exited non-zero
""", file=sys.stderr)


def main():
    args = sys.argv[1:]

    if not args or args[0] in ("-h", "--help"):
        usage()
        sys.exit(0)

    if args[0] == "--version":
        print(f"cw {VERSION}")
        sys.exit(0)

    # Subcommand: init
    if args[0] == "init":
        if "--aliases" in args:
            init_aliases()
        elif "--uninstall-aliases" in args:
            uninstall_aliases()
        else:
            print("Usage: cw init --aliases | cw init --uninstall-aliases", file=sys.stderr)
            sys.exit(1)
        return

    # Parse options, then treat rest as command
    stall_timeout = DEFAULT_STALL_TIMEOUT
    notify_delay = DEFAULT_NOTIFY_DELAY
    cmd_start = 0

    i = 0
    while i < len(args):
        if args[i] == "--stall-timeout" and i + 1 < len(args):
            stall_timeout = int(args[i + 1])
            i += 2
        elif args[i] == "--notify-delay" and i + 1 < len(args):
            notify_delay = int(args[i + 1])
            i += 2
        else:
            cmd_start = i
            break

    cmd = args[cmd_start:]
    if not cmd:
        usage()
        sys.exit(1)

    sys.exit(run_command(cmd, stall_timeout, notify_delay))


if __name__ == "__main__":
    main()
